Membership pass app
e-pass/e-pass pull request #17
Opened 2024-02-07 14:37 UTC by Salvador-Geniy

2024-02-07 15:45 UTC, Foxitch requested changes

2024-02-07 15:45 UTC, Foxitch commented on membership_passes/management/commands/passes_check.py
> +
Этот файл должен тут быть?

2024-02-07 15:45 UTC, Foxitch commented on membership_passes/check_script.sh
> +
Этот файл должен тут быть?

2024-02-07 15:45 UTC, Foxitch commented on membership_passes/permissions.py
> +from django.views import View
Думаю, пермишенны лучше складывать в приложение users + тут они дублируются

2024-02-07 15:45 UTC, Foxitch commented on membership_passes/serializer.py
> +from membership_passes.validation import (_check_expiration_total,
Зачем делать методы protected, если они импортируются в другие файлы?

2024-02-07 19:29 UTC, Salvador-Geniy commented on membership_passes/permissions.py
> +from django.views import View
Перенёс

2024-02-07 19:29 UTC, Salvador-Geniy commented on membership_passes/serializer.py
> +from membership_passes.validation import (_check_expiration_total,
Исправил

2024-02-10 12:53 UTC, Foxitch commented on ePass/settings.py
> +    'DATE_INPUT_FORMATS': [
Может лучше сделаем один стандартный формат?
YYYY-MM-DDThh:mm:ss

2024-02-11 17:38 UTC, merged